name: Promote a deployment

on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: "The tag to deploy, or leave blank to use the latest source deployment"
        required: false
      destination:
        type: string
        description: "The destination environment"
        required: true
      source-default:
        type: string
        description: "The source environment"
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      needed: ${{ steps.prepare.outputs.needed }}
      deploy_tag: ${{ steps.prepare.outputs.deploy_tag }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine deploy tag
        id: prepare
        run: |
          DEPLOY_TAG=${{ inputs.tag }}
          if [ -z "$DEPLOY_TAG" ]; then
            DEPLOY_TAG=$(<deployment/${{ inputs.source-default }}-deployment.txt)
            echo "No tag provided, using tag deployed to ${{ inputs.source-default }}: $DEPLOY_TAG"
          else
            echo "Using provided tag: $DEPLOY_TAG"
          fi
          if [ "$DEPLOY_TAG" = "$(<deployment/${{ inputs.destination }}-deployment.txt)" ]; then
            echo "Deployment is already using tag $DEPLOY_TAG"
            echo "needed=false" >> $GITHUB_OUTPUT
          else
            echo "needed=true" >> $GITHUB_OUTPUT
            echo "deploy_tag=$DEPLOY_TAG" >> $GITHUB_OUTPUT
          fi

# This job should deploy the container.
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.destination }}
    needs: prepare
    if: needs.prepare.outputs.needed == 'true'
    steps:

      - name: Deploy
        id: deploy
        run: |
          echo "Deploying ${{ needs.prepare.outputs.deploy_tag }} to ${{ inputs.destination }} in ${{ vars.REGION }}..."

  record-deployment:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - deploy
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update staging deployment file
        run: |
          echo "${{ needs.prepare.outputs.deploy_tag }}" > deployment/${{ inputs.destination }}-deployment.txt

      - name: Commit and push
        uses: actions4git/add-commit-push@v1
        with:
          commit-message: "Update ${{ inputs.destination }} deploy tag\n[skip actions]"
