name: Deploy to Test

on:
  workflow_run:
    workflows:
      - Build and Push
    types:
      - completed

jobs:
  deploy-test:
    permissions:
      contents: write
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/_promote.yaml
    with:
      source-default: none
      destination: test
      tag: ${{ github.sha }}
