name: Promote to Staging

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "The tag to deploy, or leave blank to use the latest source deployment"
        required: false

jobs:
  deploy-staging:
    permissions:
      contents: write
    uses: ./.github/workflows/_promote.yaml
    with:
      source-default: staging
      destination: production
      tag: ${{ inputs.tag }}
