name: Promote test to staging

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "The tag to deploy, or leave blank to use the latest source deployment"
        required: false

jobs:
  promote:
    permissions:
      contents: write
    uses: ./.github/workflows/_promote.yaml
    with:
      source-default: test
      destination: staging
      tag: ${{ inputs.tag }}
